/*
 * Copyright 2024 Google LLC
 *
 * @APPLE_OSREFERENCE_LICENSE_HEADER_START@
 *
 * This file contains Original Code and/or Modifications of Original Code
 * as defined in and that are subject to the Apple Public Source License
 * Version 2.0 (the 'License'). You may not use this file except in
 * compliance with the License. The rights granted to you under the License
 * may not be used to create, or enable the creation or redistribution of,
 * unlawful or unlicensed copies of an Apple operating system, or to
 * circumvent, violate, or enable the circumvention or violation of, any
 * terms of an Apple operating system software license agreement.
 *
 * Please obtain a copy of the License at
 * http://www.opensource.apple.com/apsl/ and read it before using this file.
 *
 * The Original Code and all software distributed under the License are
 * distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 * EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 * Please see the License for the specific language governing rights and
 * limitations under the License.
 *
 * @APPLE_OSREFERENCE_LICENSE_HEADER_END@
 */

/*
 * Startup trampoline for macOS arm64 build.
 *
 * Provides the global array that startup entry constructors populate,
 * and the iterate function that sorts and executes them.
 */
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define FUZZ_MAX_STARTUP_ENTRIES 4096

struct fuzz_startup_entry {
    unsigned int subsystem;
    unsigned int rank;
    void (*func)(const void *);
    const void *arg;
};

/* Global array populated by __attribute__((constructor)) functions
 * generated by the ZONE_DECLARE / STARTUP_ARG macros. */
struct fuzz_startup_entry fuzz_startup_entries[FUZZ_MAX_STARTUP_ENTRIES];
int fuzz_startup_entry_count = 0;

static int entry_compare(const void *a, const void *b) {
    const struct fuzz_startup_entry *ea = (const struct fuzz_startup_entry *)a;
    const struct fuzz_startup_entry *eb = (const struct fuzz_startup_entry *)b;
    if (ea->subsystem != eb->subsystem)
        return (ea->subsystem < eb->subsystem) ? -1 : 1;
    if (ea->rank != eb->rank)
        return (ea->rank < eb->rank) ? -1 : 1;
    return 0;
}

void startup_iterate_section(uint32_t upto, uint32_t current_phase) {
    if (fuzz_startup_entry_count == 0) return;

    /* Sort by (subsystem, rank). */
    qsort(fuzz_startup_entries, fuzz_startup_entry_count,
          sizeof(struct fuzz_startup_entry), entry_compare);

    for (int i = 0; i < fuzz_startup_entry_count; i++) {
        if (fuzz_startup_entries[i].subsystem > upto) break;
        if (fuzz_startup_entries[i].subsystem <= current_phase) continue;
        if (fuzz_startup_entries[i].func) {
            fuzz_startup_entries[i].func(fuzz_startup_entries[i].arg);
        }
    }
}
